name: Deploy Strapi Single EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      #Configure AWS credentials (ACCESS KEYS METHOD)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Verify AWS authentication
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      #Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #Build, tag & push Docker image to ECR
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: strapi-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      #Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #Terraform Init
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      #Terraform Apply (Single EC2)
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
